### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by cqm3ron** [skycatminepokie/no-hat-for-da-ground#2]
I know I'm very early, but your mod is one of the ones we would like to use on our 1.21 server so an update would be nice. No pressure though! :D

**Comment by skycatminepokie** [comment]
Nah, you're an hour late :P
I will port it, but for now, a dependency override should work.
https://fabricmc.net/wiki/tutorial:dependency_overrides

**Comment by skycatminepokie** [comment]
@cqm3ron Uploaded to [Modrinth](https://modrinth.com/mod/no-hat-for-da-ground/version/ftSzz6Hu) :)
